[package]
name = "ezsockets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
base64 = "0.13.0"
futures = "0.3.21"
http = "0.2.6"
tokio = { version = "1.17.0", features = ["sync", "rt", "macros", "time"] }
tracing = "0.1.31"
url = "2.2.2"

axum_crate = { package = "axum", version = "0.4.8", features = ["ws"], optional = true }
tokio-tungstenite = { version = "0.17.1", optional = true }
cfg-if = "1.0.0"

[features]
default = []

client = ["tokio-tungstenite"]

server = []
server-tungstenite = ["server", "tokio-tungstenite"]
server-axum = ["server", "axum_crate"]

[dev-dependencies]
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
tracing-subscriber = "0.3.9"

[[example]]
name = "client"
required-features = ["client"]

[[example]]
name = "server-axum"
required-features = ["server-axum"]

[[example]]
name = "server-tungstenite"
required-features = ["server-tungstenite"]
